argo-cd:
  enabled: true

  configs:
    params:
      server.insecure: true   # recomendado si TLS termina en ingress

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.jaelielz.es
      # hosts:
      #   - argocd.jaelielz.es

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

      tls:
        - hosts:
            - argocd.jaelielz.es
          secretName: argocd-server-tls
